% Ex_digitizeImage.m =====================================================%

% Written By: Jonathan Kratz
% Date: January 2, 2018
% Description: Follows the instruction to through this example to
% illustrate usage of the digitizeImage function.

% Instructions:
%   (1) Run this scrip to call the digitizeImage function. The function
%       will read in the "SineFunction.jpg" image file.
%   (2) Follow the input prompts to identify the origin of the image
%       (origin of the plot) and a known x,y location (for example: the
%       peak at x = pi/2, y = 1)
%   (3) Enter "y" to the prompt that asks if the data points should be
%       connected with a spline (this is optional)
%   (3) Follow the prompt to pick various points overlapping the sine
%       function in the image. Start from the left and work to the right.
%       Pick the points such that they are spaced appropriately to capture
%       the shape to the sine function. When you are done selecting the
%       last point, press "Enter". The coordinates of the selected points
%       should be returned.
% The figures "SinFunctionSplineFit.fig' and "SinFunctionPtsFromImage.fig"
% provide example of what the spline fit should resemble after the points 
% have been selected and how the selected points might compare to a sine 
% function generated by MATLAB.
%

% Digitize the Image
[ x,y ] = digitizeImage( 'SineFunction.jpg' );

% Plot Results
X = linspace(-2*pi,2*pi,100);
Y = sin(X);
figure()
plot(X,Y,'-b')
hold on
plot(x,y,'xk')
xlabel('x')
ylabel('y')
title('Sine Function Points From Image')

% Save the results
SaveRes = input('Save the results (x,y) to a MAT-file (y/n)? ','s');
if strcmp(SaveRes,'y')
    fn = input('Filename: ','s');
    save(fn,'x','y');
end